name: Build "execute"

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 16 ]
      fail-fast: true
    steps:
      # Build the things
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: mvn clean package
      - run: mkdir -p staging/${{ matrix.java }}/
      - run: cp execute-spigot/target/*.jar staging/${{ matrix.java }} # Move files
      - run: cp execute-bungeecord/target/*.jar staging/${{ matrix.java }} # Move files
      - run: cp execute-velocity/target/*.jar staging/${{ matrix.java }} # Move files
      - run: rm -r staging/${{ matrix.java }}/original-*.jar # Delete unshaded files
      - uses: actions/upload-artifact@v2 # Upload
        with:
          name: execute
          path: staging/*
          retention-days: 10 # Delete artifacts after 10 days